# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      config_file:
        description: 'Path of Mend Config file'
        default: 'wss-unified-agent-default.config'
        required: false
        type: string
      product_Name:
        description: 'Application Name'
        required: true
        type: string
      project_Name:
        description: 'Module Name'
        required: true
        type: string
      project_Version:
        description: 'Version the project if required'
        required: false
        type: string
    secrets:
      apikey:
        required: true
      userkey: 
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Download unified agent jar file
      - name: Download the unified agent scanner
        run: curl -LJO https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar
      # Runs Mend scan
      - name: Mend Scan
        run: java -jar wss-unified-agent.jar -c ${{ inputs.config_file }} -apikey ${{ secrets.apikey }} -userkey ${{ secrets.userkey }} -project ${{ inputs.project_Name }} -projectVersion ${{ inputs.project_Version }} -product ${{ inputs.product_Name }} -projectTag GitHub:$GITHUB_REPOSITORY
